version: "3"

services:
    dsc-chat-server:
        image: dsc-chat-server
        ports:
            - 3030:3030
        networks:
            - dsc
        volumes:
            - chat-server-data:/usr/src/app/data

    dsc-chat-client:
        image: dsc-chat-client
        ports:
            - 8000:8080
        networks:
            - dsc
        depends_on:
            - dsc-chat-server
        volumes:
            - ./client/config/config.json:/srv/assets/config.json
            - ./client/config/Caddyfile:/etc/caddy/Caddyfile

networks:
    dsc:

volumes:
    chat-server-data:
